language: node_js
node_js:
  - 13

services:
  - docker

deploy_service_job: &DEPLOY_SERVICE_JOB # Pre-testing installs
  install:
    - echo "nothing needs to be installed"

  # Scripts to be run such as tests
  before_script:
    - echo "no tests"

  script:
    - cd ${IMAGE_NAME}
    - docker --version # print the version for logging
    - docker build -t ${IMAGE_NAME} .
    - docker tag ${IMAGE_NAME} hashemfay/${IMAGE_NAME}:latest

  after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push hashemfay/${IMAGE_NAME}
    - cd -

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Users API"
      env:
        - IMAGE_NAME="user-api"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Feed API"
      env:
        - IMAGE_NAME="feed-api"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy App"
      env:
        - IMAGE_NAME="udacity-c2-frontend"
