apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: user-api
          image: hashemfay/user-api
          ports:
            - containerPort: 80
        - name: feed-api
          image: hashemfay/feed-api
          ports:
            - containerPort: 80
        - name: udacity-c2-frontend
          image: hashemfay/udacity-c2-frontend
          ports:
            - containerPort: 80
        - name: reverse-proxy
          image: hashemfay/reverse-proxy
          ports:
            - containerPort: 80
