version: "3"
services:
  reverseproxy:
    image: hashemfay/reverse-proxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-feed
      - backend-user
  backend-user:
    image: hashemfay/user-api
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_TOKEN: $JWT_TOKEN
      URL: "http://localhost:8100"
  backend-feed:
    image: hashemfay/feed-api
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_TOKEN: $JWT_TOKEN
      URL: "http://localhost:8100"
  frontend:
    image: hashemfay/udacity-c2-frontend:local
    ports:
      - "8100:80"
